version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            npm install
            npm run build
            npm run coverage
      - run: mkdir test-reports
      - run: sudo pip install selenium
      - run: sudo pip install requests
      - run: 
          command: python tests/test_selenium_chrome.py
          command: python tests/test_selenium_edge.py
          command: python tests/test_selenium_firefox.py
          command: python tests/test_selenium_IE.py
          command: python tests/test_selenium_safari.py
