version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
    steps:
      - checkout
      - run:
          name: Build and Test
          command: |
            mkdir test-reports
            sudo pip install selenium
            sudo pip install requests
            python test/test_selenium_chrome.py
            python test/test_selenium_edge.py
            python test/test_selenium_firefox.py
            python test/test_selenium_IE.py
            python test/test_selenium_safari.py
