version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    steps:
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Unit Test (with coverage)
          command: npm run coverage
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - run:
          name: Prepare demo
          command: ./scripts/demo.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./demo
            - ./storybook-static
  update-demos:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
              - "73:c0:27:e4:c9:d4:af:dd:0d:6c:d5:95:3c:f9:9b:fc"
      - run:
          name: Prepare
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Deploy demo
          command: |
            gh-pages --dist . -m "Update demo [ci skip]"
workflows:
  version: 2
  build:
    jobs:
      - build
      - update-demos:
          requires:
            - build
          filters:
            branches:
              only: master
